[package]
name = "xp-source"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
xp-types.workspace = true
reqwest.workspace = true
serde_json.workspace = true
async-trait.workspace = true
thiserror.workspace = true
tracing.workspace = true
hex.workspace = true

[dev-dependencies]
xp-wire.workspace = true
axum.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "macros"] }
